import type {
  Lead,
  Agent,
  Campaign,
  Workflow,
  DashboardMetrics,
  Notification,
  Integration,
} from "@/types";

// ============================================
// Dashboard Metrics
// ============================================
export const mockDashboardMetrics: DashboardMetrics = {
  leads_discovered: 2847,
  leads_contacted: 1923,
  messages_sent: 5621,
  replies_received: 847,
  meetings_booked: 234,
  conversion_rate: 12.2,
  response_rate: 44.0,
  active_campaigns: 8,
  agents_running: 5,
  pipeline_value: 1250000,
  leads_trend: [
    { date: "2026-03-13", value: 32 },
    { date: "2026-03-14", value: 45 },
    { date: "2026-03-15", value: 28 },
    { date: "2026-03-16", value: 56 },
    { date: "2026-03-17", value: 42 },
    { date: "2026-03-18", value: 67 },
    { date: "2026-03-19", value: 53 },
    { date: "2026-03-20", value: 71 },
    { date: "2026-03-21", value: 48 },
    { date: "2026-03-22", value: 63 },
    { date: "2026-03-23", value: 89 },
    { date: "2026-03-24", value: 74 },
    { date: "2026-03-25", value: 92 },
    { date: "2026-03-26", value: 85 },
  ],
  meetings_trend: [
    { date: "2026-03-13", value: 3 },
    { date: "2026-03-14", value: 5 },
    { date: "2026-03-15", value: 2 },
    { date: "2026-03-16", value: 7 },
    { date: "2026-03-17", value: 4 },
    { date: "2026-03-18", value: 8 },
    { date: "2026-03-19", value: 6 },
    { date: "2026-03-20", value: 9 },
    { date: "2026-03-21", value: 5 },
    { date: "2026-03-22", value: 7 },
    { date: "2026-03-23", value: 11 },
    { date: "2026-03-24", value: 8 },
    { date: "2026-03-25", value: 12 },
    { date: "2026-03-26", value: 10 },
  ],
  channel_performance: [
    { channel: "Email", sent: 3200, opened: 1440, replied: 512, meetings: 142 },
    { channel: "LinkedIn", sent: 1800, opened: 990, replied: 270, meetings: 72 },
    { channel: "WhatsApp", sent: 621, opened: 558, replied: 65, meetings: 20 },
  ],
  top_performing_campaigns: [
    { id: "1", name: "Series A SaaS Founders", sent: 450, replies: 89, meetings: 34, conversion_rate: 7.6 },
    { id: "2", name: "E-commerce Directors", sent: 380, replies: 72, meetings: 28, conversion_rate: 7.4 },
    { id: "3", name: "VP Engineering Outreach", sent: 520, replies: 94, meetings: 31, conversion_rate: 6.0 },
    { id: "4", name: "Healthcare CTO Connect", sent: 290, replies: 51, meetings: 19, conversion_rate: 6.6 },
  ],
};

// ============================================
// Leads
// ============================================
export const mockLeads: Lead[] = [
  {
    id: "lead-1",
    company_id: "comp-1",
    first_name: "Sarah",
    last_name: "Chen",
    email: "sarah.chen@techflow.io",
    phone: "+1-415-555-0142",
    job_title: "VP of Engineering",
    company_name: "TechFlow",
    company_website: "https://techflow.io",
    company_size: "50-200",
    industry: "SaaS",
    linkedin_url: "https://linkedin.com/in/sarachen",
    location: "San Francisco, CA",
    status: "meeting_booked",
    score: 92,
    pain_points: ["Scaling engineering team", "Dev productivity tooling"],
    research_notes: "Recently raised Series B. Hiring aggressively. Pain point around developer onboarding.",
    source: "LinkedIn Search",
    tags: ["high-priority", "series-b", "saas"],
    last_contacted_at: "2026-04-10T14:30:00Z",
    meeting_scheduled_at: "2026-04-15T10:00:00Z",
    created_at: "2026-04-05T09:00:00Z",
    updated_at: "2026-04-10T14:30:00Z",
  },
  {
    id: "lead-2",
    company_id: "comp-1",
    first_name: "Marcus",
    last_name: "Rivera",
    email: "marcus@growthmetrics.com",
    job_title: "CTO",
    company_name: "GrowthMetrics",
    company_website: "https://growthmetrics.com",
    company_size: "200-500",
    industry: "Analytics",
    linkedin_url: "https://linkedin.com/in/marcusrivera",
    location: "New York, NY",
    status: "replied",
    score: 85,
    pain_points: ["Data pipeline reliability", "Real-time analytics"],
    research_notes: "Expanding into enterprise market. Needs better data infrastructure.",
    source: "Web Scraping",
    tags: ["enterprise", "analytics"],
    last_contacted_at: "2026-04-09T11:15:00Z",
    created_at: "2026-04-03T08:00:00Z",
    updated_at: "2026-04-09T11:15:00Z",
  },
  {
    id: "lead-3",
    company_id: "comp-1",
    first_name: "Emily",
    last_name: "Nakamura",
    email: "emily.n@cloudscale.dev",
    job_title: "Head of Product",
    company_name: "CloudScale",
    company_website: "https://cloudscale.dev",
    company_size: "50-200",
    industry: "Cloud Infrastructure",
    linkedin_url: "https://linkedin.com/in/emilynakamura",
    location: "Seattle, WA",
    status: "contacted",
    score: 78,
    pain_points: ["Product-market fit", "Enterprise sales motion"],
    source: "Database Search",
    tags: ["cloud", "infrastructure"],
    last_contacted_at: "2026-04-11T09:00:00Z",
    created_at: "2026-04-06T10:00:00Z",
    updated_at: "2026-04-11T09:00:00Z",
  },
  {
    id: "lead-4",
    company_id: "comp-1",
    first_name: "David",
    last_name: "Okonkwo",
    email: "david@finleap.com",
    job_title: "CEO",
    company_name: "FinLeap",
    company_website: "https://finleap.com",
    company_size: "10-50",
    industry: "FinTech",
    linkedin_url: "https://linkedin.com/in/davidokonkwo",
    location: "Austin, TX",
    status: "interested",
    score: 88,
    pain_points: ["Customer acquisition cost", "Regulatory compliance automation"],
    research_notes: "Pre-Series A. Backed by YC. Very responsive to cold outreach.",
    source: "LinkedIn Search",
    tags: ["fintech", "startup", "yc"],
    last_contacted_at: "2026-04-10T16:45:00Z",
    created_at: "2026-04-04T12:00:00Z",
    updated_at: "2026-04-10T16:45:00Z",
  },
  {
    id: "lead-5",
    company_id: "comp-1",
    first_name: "Priya",
    last_name: "Sharma",
    email: "priya@healthbridge.ai",
    job_title: "COO",
    company_name: "HealthBridge AI",
    company_website: "https://healthbridge.ai",
    company_size: "200-500",
    industry: "Healthcare Tech",
    linkedin_url: "https://linkedin.com/in/priyasharma",
    location: "Boston, MA",
    status: "qualified",
    score: 95,
    pain_points: ["Operational efficiency", "Patient data integration"],
    research_notes: "Series C. Expanding into new markets. Actively looking for partners.",
    source: "Referral",
    tags: ["healthcare", "enterprise", "hot-lead"],
    last_contacted_at: "2026-04-11T08:30:00Z",
    meeting_scheduled_at: "2026-04-14T15:00:00Z",
    created_at: "2026-04-01T07:00:00Z",
    updated_at: "2026-04-11T08:30:00Z",
  },
  {
    id: "lead-6",
    company_id: "comp-1",
    first_name: "James",
    last_name: "Mitchell",
    email: "james.m@retailnext.co",
    job_title: "Director of Sales",
    company_name: "RetailNext",
    company_website: "https://retailnext.co",
    company_size: "500-1000",
    industry: "E-commerce",
    location: "Chicago, IL",
    status: "new",
    score: 62,
    pain_points: ["Omnichannel retail", "Inventory optimization"],
    source: "Web Scraping",
    tags: ["retail", "enterprise"],
    created_at: "2026-04-11T15:00:00Z",
    updated_at: "2026-04-11T15:00:00Z",
  },
  {
    id: "lead-7",
    company_id: "comp-1",
    first_name: "Lisa",
    last_name: "Wang",
    email: "lisa@quantum-labs.io",
    job_title: "CTO",
    company_name: "Quantum Labs",
    company_website: "https://quantum-labs.io",
    company_size: "10-50",
    industry: "Deep Tech",
    linkedin_url: "https://linkedin.com/in/lisawang",
    location: "Palo Alto, CA",
    status: "researched",
    score: 71,
    pain_points: ["Go-to-market strategy", "Technical talent acquisition"],
    research_notes: "PhD-led team. Strong tech but early in commercialization.",
    source: "Database Search",
    tags: ["deeptech", "startup"],
    created_at: "2026-04-10T11:00:00Z",
    updated_at: "2026-04-10T11:00:00Z",
  },
  {
    id: "lead-8",
    company_id: "comp-1",
    first_name: "Robert",
    last_name: "Kim",
    email: "rkim@logisticspro.com",
    job_title: "VP Operations",
    company_name: "LogisticsPro",
    company_website: "https://logisticspro.com",
    company_size: "1000+",
    industry: "Logistics",
    location: "Miami, FL",
    status: "unresponsive",
    score: 45,
    source: "LinkedIn Search",
    tags: ["logistics", "enterprise"],
    last_contacted_at: "2026-03-28T10:00:00Z",
    created_at: "2026-03-25T08:00:00Z",
    updated_at: "2026-03-28T10:00:00Z",
  },
];

// ============================================
// Agents
// ============================================
export const mockAgents: Agent[] = [
  {
    id: "agent-1",
    company_id: "comp-1",
    type: "prospect_finder",
    name: "Prospect Finder",
    description: "Searches the internet and databases to identify companies matching your ICP",
    status: "running",
    config: { sources: ["linkedin", "crunchbase", "web"], max_results_per_run: 50 },
    last_run_at: "2026-04-12T08:00:00Z",
    tasks_completed: 1247,
    tasks_failed: 23,
    success_rate: 98.2,
    created_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "agent-2",
    company_id: "comp-1",
    type: "research",
    name: "Research Agent",
    description: "Analyzes prospect websites, extracts pain points, and builds intel profiles",
    status: "running",
    config: { depth: "deep", extract_technographics: true },
    last_run_at: "2026-04-12T07:45:00Z",
    tasks_completed: 934,
    tasks_failed: 41,
    success_rate: 95.8,
    created_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "agent-3",
    company_id: "comp-1",
    type: "personalization",
    name: "Personalization Agent",
    description: "Crafts custom outreach messages based on research insights and pain points",
    status: "running",
    config: { tone: "professional", max_length: 150, include_question: true },
    last_run_at: "2026-04-12T07:30:00Z",
    tasks_completed: 2156,
    tasks_failed: 12,
    success_rate: 99.4,
    created_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "agent-4",
    company_id: "comp-1",
    type: "outreach",
    name: "Outreach Agent",
    description: "Sends personalized emails and LinkedIn messages with A/B variation rotation",
    status: "running",
    config: { channels: ["email", "linkedin"], daily_limit: 100, send_window: "9am-5pm" },
    last_run_at: "2026-04-12T09:00:00Z",
    tasks_completed: 5621,
    tasks_failed: 87,
    success_rate: 98.5,
    created_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "agent-5",
    company_id: "comp-1",
    type: "follow_up",
    name: "Follow-up Agent",
    description: "Automatically schedules and sends follow-up sequences at optimal times",
    status: "running",
    config: { max_follow_ups: 4, wait_days: [3, 5, 7, 14] },
    last_run_at: "2026-04-12T08:15:00Z",
    tasks_completed: 3412,
    tasks_failed: 56,
    success_rate: 98.4,
    created_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "agent-6",
    company_id: "comp-1",
    type: "meeting",
    name: "Meeting Agent",
    description: "Detects buying intent and books calls directly into your calendar",
    status: "idle",
    config: { calendar: "calendly", duration: 30, buffer_minutes: 15 },
    last_run_at: "2026-04-11T17:00:00Z",
    tasks_completed: 234,
    tasks_failed: 8,
    success_rate: 96.7,
    created_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "agent-7",
    company_id: "comp-1",
    type: "crm",
    name: "CRM Agent",
    description: "Automatically updates your pipeline, logs activities, and syncs contacts",
    status: "running",
    config: { crm: "hubspot", sync_interval: "5m", auto_stage: true },
    last_run_at: "2026-04-12T09:05:00Z",
    tasks_completed: 8934,
    tasks_failed: 34,
    success_rate: 99.6,
    created_at: "2026-03-01T00:00:00Z",
  },
];

// ============================================
// Campaigns
// ============================================
export const mockCampaigns: Campaign[] = [
  {
    id: "camp-1",
    company_id: "comp-1",
    name: "Series A SaaS Founders",
    description: "Targeting recently funded SaaS founders for platform demo",
    status: "active",
    channel: "multi",
    leads_count: 450,
    sent_count: 380,
    opened_count: 228,
    replied_count: 89,
    meetings_booked: 34,
    sequence_steps: [
      { id: "s1", order: 1, type: "email", subject: "Quick question about {{company_name}}", body: "Hi {{first_name}}..." },
      { id: "s2", order: 2, type: "wait", wait_days: 3 },
      { id: "s3", order: 3, type: "linkedin_connect", body: "Hi {{first_name}}, I noticed..." },
      { id: "s4", order: 4, type: "wait", wait_days: 2 },
      { id: "s5", order: 5, type: "email", subject: "Re: Quick question", body: "Just following up..." },
      { id: "s6", order: 6, type: "wait", wait_days: 5 },
      { id: "s7", order: 7, type: "linkedin_message", body: "Hi {{first_name}}, wanted to share..." },
    ],
    start_date: "2026-03-15",
    created_at: "2026-03-10T00:00:00Z",
  },
  {
    id: "camp-2",
    company_id: "comp-1",
    name: "E-commerce Directors",
    description: "Outreach to e-commerce leaders for Q2 push",
    status: "active",
    channel: "email",
    leads_count: 380,
    sent_count: 320,
    opened_count: 192,
    replied_count: 72,
    meetings_booked: 28,
    sequence_steps: [
      { id: "s1", order: 1, type: "email", subject: "{{company_name}}'s growth potential", body: "Hi {{first_name}}..." },
      { id: "s2", order: 2, type: "wait", wait_days: 4 },
      { id: "s3", order: 3, type: "email", subject: "Case study you might like", body: "Quick follow up..." },
    ],
    start_date: "2026-03-20",
    created_at: "2026-03-18T00:00:00Z",
  },
  {
    id: "camp-3",
    company_id: "comp-1",
    name: "VP Engineering Outreach",
    description: "Targeting VPs of Engineering at mid-market companies",
    status: "active",
    channel: "linkedin",
    leads_count: 520,
    sent_count: 440,
    opened_count: 308,
    replied_count: 94,
    meetings_booked: 31,
    sequence_steps: [
      { id: "s1", order: 1, type: "linkedin_connect", body: "Hi {{first_name}}..." },
      { id: "s2", order: 2, type: "wait", wait_days: 2 },
      { id: "s3", order: 3, type: "linkedin_message", body: "Thanks for connecting..." },
    ],
    start_date: "2026-03-25",
    created_at: "2026-03-22T00:00:00Z",
  },
  {
    id: "camp-4",
    company_id: "comp-1",
    name: "Healthcare CTO Connect",
    description: "Engaging healthcare tech leaders",
    status: "paused",
    channel: "email",
    leads_count: 290,
    sent_count: 210,
    opened_count: 126,
    replied_count: 51,
    meetings_booked: 19,
    sequence_steps: [
      { id: "s1", order: 1, type: "email", subject: "Healthcare innovation", body: "Hi {{first_name}}..." },
      { id: "s2", order: 2, type: "wait", wait_days: 5 },
      { id: "s3", order: 3, type: "email", subject: "Following up", body: "Hi again..." },
    ],
    start_date: "2026-04-01",
    created_at: "2026-03-28T00:00:00Z",
  },
  {
    id: "camp-5",
    company_id: "comp-1",
    name: "FinTech Decision Makers",
    description: "Targeting C-suite at fintech startups",
    status: "draft",
    channel: "multi",
    leads_count: 0,
    sent_count: 0,
    opened_count: 0,
    replied_count: 0,
    meetings_booked: 0,
    sequence_steps: [],
    created_at: "2026-04-10T00:00:00Z",
  },
];

// ============================================
// Workflows
// ============================================
export const mockWorkflows: Workflow[] = [
  {
    id: "wf-1",
    company_id: "comp-1",
    name: "New Lead Processing",
    description: "Automatically research and qualify new leads",
    status: "active",
    trigger: { type: "new_lead", config: {} },
    nodes: [
      { id: "n1", type: "trigger", position: { x: 250, y: 50 }, data: { label: "New Lead Added", config: {} } },
      { id: "n2", type: "ai_agent", position: { x: 250, y: 150 }, data: { label: "Research Agent", description: "Analyze company", config: { agent: "research" } } },
      { id: "n3", type: "ai_agent", position: { x: 250, y: 250 }, data: { label: "Score Lead", description: "Calculate fit score", config: { agent: "scoring" } } },
      { id: "n4", type: "condition", position: { x: 250, y: 350 }, data: { label: "Score > 70?", config: { field: "score", operator: "gt", value: 70 } } },
      { id: "n5", type: "ai_agent", position: { x: 100, y: 450 }, data: { label: "Personalize Message", config: { agent: "personalization" } } },
      { id: "n6", type: "action", position: { x: 400, y: 450 }, data: { label: "Add to Nurture", config: { action: "add_to_campaign" } } },
      { id: "n7", type: "action", position: { x: 100, y: 550 }, data: { label: "Send Outreach", config: { action: "send_message" } } },
    ],
    edges: [
      { id: "e1", source: "n1", target: "n2" },
      { id: "e2", source: "n2", target: "n3" },
      { id: "e3", source: "n3", target: "n4" },
      { id: "e4", source: "n4", target: "n5", label: "Yes" },
      { id: "e5", source: "n4", target: "n6", label: "No" },
      { id: "e6", source: "n5", target: "n7" },
    ],
    created_at: "2026-03-15T00:00:00Z",
  },
  {
    id: "wf-2",
    company_id: "comp-1",
    name: "Reply Handler",
    description: "Process and route incoming replies",
    status: "active",
    trigger: { type: "reply_received", config: {} },
    nodes: [
      { id: "n1", type: "trigger", position: { x: 250, y: 50 }, data: { label: "Reply Received", config: {} } },
      { id: "n2", type: "ai_agent", position: { x: 250, y: 150 }, data: { label: "Analyze Sentiment", config: { agent: "analysis" } } },
      { id: "n3", type: "condition", position: { x: 250, y: 250 }, data: { label: "Positive?", config: { field: "sentiment", operator: "eq", value: "positive" } } },
      { id: "n4", type: "ai_agent", position: { x: 100, y: 350 }, data: { label: "Book Meeting", config: { agent: "meeting" } } },
      { id: "n5", type: "action", position: { x: 400, y: 350 }, data: { label: "Notify Team", config: { action: "notify" } } },
    ],
    edges: [
      { id: "e1", source: "n1", target: "n2" },
      { id: "e2", source: "n2", target: "n3" },
      { id: "e3", source: "n3", target: "n4", label: "Yes" },
      { id: "e4", source: "n3", target: "n5", label: "No" },
    ],
    created_at: "2026-03-20T00:00:00Z",
  },
  {
    id: "wf-3",
    company_id: "comp-1",
    name: "Meeting Follow-up",
    description: "Post-meeting automated follow-up sequence",
    status: "active",
    trigger: { type: "meeting_booked", config: {} },
    nodes: [
      { id: "n1", type: "trigger", position: { x: 250, y: 50 }, data: { label: "Meeting Booked", config: {} } },
      { id: "n2", type: "action", position: { x: 250, y: 150 }, data: { label: "Update CRM", config: { action: "update_crm" } } },
      { id: "n3", type: "delay", position: { x: 250, y: 250 }, data: { label: "Wait 1 Day", config: { days: 1 } } },
      { id: "n4", type: "action", position: { x: 250, y: 350 }, data: { label: "Send Prep Email", config: { action: "send_email" } } },
    ],
    edges: [
      { id: "e1", source: "n1", target: "n2" },
      { id: "e2", source: "n2", target: "n3" },
      { id: "e3", source: "n3", target: "n4" },
    ],
    created_at: "2026-03-25T00:00:00Z",
  },
];

// ============================================
// Notifications
// ============================================
export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    user_id: "user-1",
    type: "meeting_booked",
    title: "Meeting Booked",
    message: "Sarah Chen from TechFlow booked a meeting for April 15 at 10:00 AM",
    read: false,
    action_url: "/dashboard/leads",
    created_at: "2026-04-12T08:30:00Z",
  },
  {
    id: "notif-2",
    user_id: "user-1",
    type: "reply_received",
    title: "New Reply",
    message: "Marcus Rivera from GrowthMetrics replied to your outreach email",
    read: false,
    action_url: "/dashboard/leads",
    created_at: "2026-04-12T07:15:00Z",
  },
  {
    id: "notif-3",
    user_id: "user-1",
    type: "lead_found",
    title: "12 New Leads Found",
    message: "Prospect Finder discovered 12 new leads matching your ICP",
    read: false,
    action_url: "/dashboard/leads",
    created_at: "2026-04-12T06:00:00Z",
  },
  {
    id: "notif-4",
    user_id: "user-1",
    type: "system",
    title: "Campaign Performance",
    message: "Series A SaaS Founders campaign hit 7.6% conversion rate",
    read: true,
    action_url: "/dashboard/campaigns",
    created_at: "2026-04-11T18:00:00Z",
  },
  {
    id: "notif-5",
    user_id: "user-1",
    type: "agent_error",
    title: "Agent Warning",
    message: "LinkedIn rate limit approaching. Outreach Agent slowed down.",
    read: true,
    action_url: "/dashboard/agents",
    created_at: "2026-04-11T14:00:00Z",
  },
];

// ============================================
// Integrations
// ============================================
export const mockIntegrations: Integration[] = [
  {
    id: "int-1",
    company_id: "comp-1",
    type: "gmail",
    status: "connected",
    config: { email: "outreach@company.com", daily_limit: 200 },
    last_synced_at: "2026-04-12T09:00:00Z",
    created_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "int-2",
    company_id: "comp-1",
    type: "linkedin",
    status: "connected",
    config: { profile: "company-linkedin", daily_limit: 50 },
    last_synced_at: "2026-04-12T08:30:00Z",
    created_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "int-3",
    company_id: "comp-1",
    type: "calendly",
    status: "connected",
    config: { link: "https://calendly.com/company/30min" },
    last_synced_at: "2026-04-12T09:05:00Z",
    created_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "int-4",
    company_id: "comp-1",
    type: "hubspot",
    status: "connected",
    config: { portal_id: "12345" },
    last_synced_at: "2026-04-12T08:45:00Z",
    created_at: "2026-03-05T00:00:00Z",
  },
  {
    id: "int-5",
    company_id: "comp-1",
    type: "slack",
    status: "connected",
    config: { channel: "#sales-notifications" },
    last_synced_at: "2026-04-12T09:00:00Z",
    created_at: "2026-03-10T00:00:00Z",
  },
  {
    id: "int-6",
    company_id: "comp-1",
    type: "outlook",
    status: "disconnected",
    config: {},
    created_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "int-7",
    company_id: "comp-1",
    type: "whatsapp",
    status: "disconnected",
    config: {},
    created_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "int-8",
    company_id: "comp-1",
    type: "salesforce",
    status: "disconnected",
    config: {},
    created_at: "2026-03-01T00:00:00Z",
  },
];
